[build]
command = "npm run build"
publish = "dist" # or "out" for Next.js or "build" for React
# If you're using a monorepo or specific app directory, specify:
# base = "apps/web" (only if necessary)
