name: Sync README and Notify Slack

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install  # or use npm install if you're not using pnpm

      - name: Run update script
        run: pnpm run update-readme  # or npm run update-readme
